language: r
cache: packages
dist: trusty
sudo: false
warnings_are_errors: false
bioc_required: true
before_install:
- Rscript -e 'update.packages(ask = FALSE)'
r_build_args: "--no-build-vignettes"
r_check_args: "--no-vignettes --no-build-vignettes --as-cran"
addons:
  apt:
    packages:
    - libmpfr-dev
notifications:
  slack:
    secure: tlFvDLkDeElfBYMSfnMJdQ5QRTqt0XPcgc8FoPj2B6lpZgL9wlAEsQVw/xnGS7kC3YMWOSWoD5Ikjq+H6AltW8aI72sdIW+UmWMvD6G9oxyhdXj0IxaW/CtyRrTYsHWmNAHr5dukZhZX9oVLKvyQ9fjm6GrfCSnFCqR2LhY1lkHrcbjAdlDi5QxWVmtRlrguqle9VQ3Hf69V+8phdx4zcsqOq2vSEbDuj2mSI9UbdYlNojkWCziCQRLjvDdKEm/o0l0yQ5Gd5vPgutol1HCEtmCMVVcmqws0bf6W4rKhnhwrcNll8DgH3Vs+vXTBIWmIemW11kdiBVr/B7Gk6CUXVrLZFa0Mlzm9nvzJMFWO+UU38UgTqw9st3a9+159GaJnzBkyoOI1QMadLdTGpuWD25hploJ8nzAdTl1MIzYZIV3Wt+dVfZ9URqdn5k3OduUjJQf4TJJr1YauF2J3xiOClorJK+Aec8oqqWFqYp77jlcGCqoMi8jZds82WFEMdS/K7ri7q6aLemFxr54wWZsL4KkjPOXJ+umvreXmpjCIBc1d+fhTcmWIiCygYBTLW04V0dXfw/Hw2EeaVcjBfOFKgoyioW4j/eT32kumzo0n6/x8oIcVc4TEytV5QnyTTVk/I/Lj7t0id22N2OZAewm0GZnvH7JFX4qvXWMmdNgmzT8=
r_github_packages:
- r-lib/covr
after_success:
- Rscript -e 'covr::coveralls()'
