language: r
cache: packages
dist: trusty
sudo: false
warnings_are_errors: true
bioc_required: true
before_install:
- Rscript -e 'update.packages(ask = FALSE)'
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"
addons:
  apt:
    packages:
    - libmpfr-dev