#' A toy count matrix for use with celda. 
#'
#' @title sample.cells
#' @description A matrix of simulated gene counts
#' @format A matrix of simulated gene counts with 10 rows (genes) and 10 columns
#' (cells)
#' @details Generated by Josh Campbell
#' @source \url{http://github.com/definitelysean/celda}
"sample.cells"

#' Perplexity plot created with the pbmc_res model. 
#'
#' @title calc.perplexity
#' @description The result of running the resamplePerplexity function on the pbmc_res model
#' @format list
#' @details Generated by Yusuke Koga
#' @source \url{http://github.com/compbiomed/celda}
"calc.perplexity"

#' Perplexity plot created with the pbmc_res model, 2nd-pass. 
#'
#' @title calc.perplexity2
#' @description The result of running the resamplePerplexity function on the pbmc_res model. Done on K = 10:20, L = 10:50
#' @format list
#' @details Generated by Yusuke Koga
#' @source \url{http://github.com/compbiomed/celda}
"calc.perplexity2"
