#' A toy count matrix for use with celda. 
#'
#' @title sample.cells
#' @description A matrix of simulated gene counts
#' @format A matrix of simulated gene counts with 10 rows (genes) and 10 columns
#' (cells)
#' @details Generated by Josh Campbell
#' @source \url{http://github.com/definitelysean/celda}
"sample.cells"

#' 3000 Peripheral Blood Mononuclear Cells (PBMC) from 10X Genomics.
#'
#' @title pbmc_select
#' @description A dataset of 3000 Peripheral Blood Mononuclear Cells (PBMC),
#' available from 10X Genomics.  The raw dataset can be found at the URL below.
#' @format The rows are organized by gene names, while the
#' columns are organized by barcodes. For this tutorial, the dataset has been
#' slightly modified so the rownames are comprised of the Ensembl gene ID as
#' well as the gene name.
#' @source \url{https://support.10xgenomics.com/single-cell/software/pipelines/latest/rkit}
"pbmc_select"

#' Celda model created from 3000 Peripheral Blood Mononuclear Cells (PBMC) from 10X Genomics.
#'
#' @title pbmc_res
#' @description A celda model made from pbmc_data, run with parameters K = 10:30 and L = 20,30.
#' @source \url{https://support.10xgenomics.com/single-cell/software/pipelines/latest/rkit}
"pbmc_res"

#' Perplexity plot created with the pbmc_res model. 
#'
#' @title calc.perplexity
#' @description The result of running the resamplePerplexity function on the pbmc_res model
#' @format list
#' @details Generated by Yusuke Koga
#' @source \url{http://github.com/compbiomed/celda}
"calc.perplexity"

#' Perplexity plot created with the pbmc_res model, 2nd-pass. 
#'
#' @title calc.perplexity2
#' @description The result of running the resamplePerplexity function on the pbmc_res model. Done on K = 10:20, L = 10:50
#' @format list
#' @details Generated by Yusuke Koga
#' @source \url{http://github.com/compbiomed/celda}
"calc.perplexity2"


#' A toy contamination data generated by simulateObservedMatrix
#'
#' @title contamination.sim
#' @description Generated by simulateObservedMatrix
#' @format A list
"contamination.sim"
