#' A toy count matrix for use with celda. 
#'
#' @title sample.cells
#' @description A matrix of simulated gene counts
#' @format A matrix of simulated gene counts with 10 rows (genes) and 10 columns
#' (cells)
#' @details Generated by Josh Campbell
#' @source \url{http://github.com/definitelysean/celda}
"sample.cells"

#' An example simulated count matrix from the celda_CG model.
#' 
#' @title celda.CG.sim
#' @format A list of counts and properties as returned from simulateCells()
#' @examples 
#' celda.CG.sim = simulateCells("celda_CG")
"celda.CG.sim"

#' celda_CG results generated from celda.CG.sim
#' 
#' @title celda.CG.mod
#' @format A celda_CG object
#' @examples 
#' celda.CG.mod = celda_CG(celda.CG.sim$counts, K=celda.CG.sim$K,
#'                         L=celda.CG.sim$L, nchains=1)
"celda.CG.mod"