# The DecontX plotting functions are maintained in the standalone decontX
# package as of celda 1.23.0. The functions below are thin wrappers that
# delegate to decontX so the implementation lives in a single place.


#' @title Plots contamination on UMAP coordinates
#' @description A scatter plot of the UMAP dimensions generated by DecontX with
#' cells colored by the estimated percentation of contamation. As of celda
#' 1.23.0 this is a thin wrapper around
#' \code{\link[decontX]{plotDecontXContamination}} in the \pkg{decontX} package,
#' which must be installed.
#' @param x Either a \linkS4class{SingleCellExperiment} with \code{decontX}
#' results stored in \code{metadata(x)$decontX} or the result from running
#' decontX on a count matrix.
#' @param ... Additional arguments passed to
#' \code{\link[decontX]{plotDecontXContamination}} (for example \code{batch},
#' \code{colorScale}, \code{size}).
#' @return Returns a \code{ggplot} object.
#' @author Shiyi Yang, Joshua Campbell
#' @seealso \code{\link[decontX]{plotDecontXContamination}}. See
#' \code{\link{decontX}} for a full example of how to estimate and plot
#' contamination.
#' @export
plotDecontXContamination <- function(x, ...) {
  .requireDecontX()
  decontX::plotDecontXContamination(x, ...)
}


#' @title Plots percentage of cells cell types expressing markers
#' @description Generates a barplot that shows the percentage of
#' cells within clusters or cell types that have detectable levels
#' of given marker genes. Can be used to view the expression of
#' marker genes in different cell types before and after
#' decontamination with \code{\link{decontX}}. As of celda 1.23.0 this is a
#' thin wrapper around \code{\link[decontX]{plotDecontXMarkerPercentage}} in the
#' \pkg{decontX} package, which must be installed.
#' @param x Either a \linkS4class{SingleCellExperiment} or
#' a matrix-like object of counts.
#' @param markers List. A named list indicating the marker genes
#' for each cell type of interest.
#' @param ... Additional arguments passed to
#' \code{\link[decontX]{plotDecontXMarkerPercentage}} (for example
#' \code{groupClusters}, \code{assayName}, \code{z}, \code{threshold},
#' \code{exactMatch}, \code{by}, \code{ncol}, \code{labelBars},
#' \code{labelSize}).
#' @return Returns a \code{ggplot} object.
#' @author Shiyi Yang, Joshua Campbell
#' @seealso \code{\link[decontX]{plotDecontXMarkerPercentage}}. See
#' \code{\link{decontX}} for a full example of how to estimate and plot
#' contamination.
#' @export
plotDecontXMarkerPercentage <- function(x, markers, ...) {
  .requireDecontX()
  decontX::plotDecontXMarkerPercentage(x, markers, ...)
}


#' @title Plots expression of marker genes before and after decontamination
#' @description Generates a violin plot that shows the expression of marker
#' genes across clusters or cell types. Can be used to view the expression of
#' marker genes in different cell types before and after decontamination with
#' \code{\link{decontX}}. As of celda 1.23.0 this is a thin wrapper around
#' \code{\link[decontX]{plotDecontXMarkerExpression}} in the \pkg{decontX}
#' package, which must be installed.
#' @param x Either a \linkS4class{SingleCellExperiment} or
#' a matrix-like object of counts.
#' @param markers List or vector of marker genes to plot.
#' @param ... Additional arguments passed to
#' \code{\link[decontX]{plotDecontXMarkerExpression}} (for example
#' \code{groupClusters}, \code{assayName}, \code{z}, \code{exactMatch},
#' \code{by}, \code{log1p}, \code{ncol}, \code{plotDots}, \code{dotSize}).
#' @return Returns a \code{ggplot} object.
#' @author Shiyi Yang, Joshua Campbell
#' @seealso \code{\link[decontX]{plotDecontXMarkerExpression}}. See
#' \code{\link{decontX}} for a full example of how to estimate and plot
#' contamination.
#' @export
plotDecontXMarkerExpression <- function(x, markers, ...) {
  .requireDecontX()
  decontX::plotDecontXMarkerExpression(x, markers, ...)
}
