# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast matrix multiplication for double x int
#' 
#' @param A Numeric matrix. Dimension G x K matrix of genes by cell population probabilities. 
#' @param B Integer matrix. Dimensions G x M. Matrix of gene counts by cell. 
#' @return An integer matrix representing the product of A and B
eigenMatMultInt <- function(A, B) {
    .Call('_celda_eigenMatMultInt', PACKAGE = 'celda', A, B)
}

